---
project:
  type: book

book:
  title: "mybook"
  author: "Jane Doe"
  date: "8/18/2021"
  chapters:
    - regression_transparency_any_change/regression_transparency_Any change.html
    - regression_transparency_ext_p/regression_transparency_Foreign participation.html
    - regression_transparency_inverse_prom/regression_transparency_Inverse prominent part. in main group.html
    - regression_transparency_level_assets_attr_inv/regression_transparency_Level assets attributable to inverse main group.html
    - regression_transparency_level_assets_attr_main/regression_transparency_Level assets attributable to main group.html
    - regression_transparency_level_assets_attr_main_positive/regression_transparency_Level assets attributable to main group (positive).html
    - regression_transparency_levels_assets_attr_domestic/regression_transparency_Level assets attributable domestic.html
    - regression_transparency_levels_assets_attr_haven/regression_transparency_Levels assets attributable to tax havens.html
    - regression_transparency_levels_assets_attr_haven_positive/regression_transparency_Levels assets attributable to tax havens (positive).html
    - regression_transparency_levels_assets_attr_nonhaven/regression_transparency_Levels assets attributable to non tax havens.html
    - regression_transparency_levels_assets_attr_nonhaven_positive/regression_transparency_Levels assets attributable to non tax havens (positive).html
    - regression_transparency_log_assets_attr_dom/regression_transparency_Log assets attributable domestic.html
    - regression_transparency_log_assets_attr_ext/regression_transparency_Log assets attributable to non tax havens (positive).html
    - regression_transparency_log_assets_attr_pff/regression_transparency_Log assets attributable to tax havens (positive).html
    - regression_transparency_log_assets_inv/regression_transparency_Log assets attributable to inverse main group.html
    - regression_transparency_log_assets_prominent/regression_transparency_Log assets attributable to main group.html
    - regression_transparency_log_cit_liability/regression_transparency_Log(CIT liability).html
    - regression_transparency_log_taxable_profits/regression_transparency_Log(Taxable profits).html
    - regression_transparency_log_utility/regression_transparency_Log(Profits).html
    - regression_transparency_nac_p/regression_transparency_Domestic participation.html
    - regression_transparency_pff_p/regression_transparency_Tax haven participation.html
    - regression_transparency_positive_profits/regression_transparency_Positive profits.html
    - regression_transparency_prominent/regression_transparency_Prominent participation in main group.html
    - regression_transparency_tasa_ir/regression_transparency_Income tax rate.html

  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
---